deployment:
  hooks:
    pre: |
      echo "Before deployment general execute"
    post: |
      echo "After deployment general"
    pre-install: |
      echo "Before running system:install"
    post-install: |
      echo "After running system:install"
    pre-update: |
      echo "Before running system:update"
    post-update: |
      echo "After running system:update"

  # Automatically installs and updates all extensions included in custom/plugins and custom/apps and composer
  extension-management:
    enabled: true

    # These extensions are not managed, you should use one-time-tasks to manage them
    exclude:
      - Name

    # These extensions are always updated even if their version does not change
    # This is useful for project-specific plugins that are not versioned
    force-update:
      - Name

  overrides:
    ProdataBaseTheme:
      state: active

  # runs one time in deployment, then never again
  one-time-tasks:
#    - id: build-storefront
#      script: |
#        ./bin/build-storefront.sh
#
#    - id: build-administration
#      script: |
#        ./bin/build-administration.sh

    - id: set-default-theme
      script: |
        ./bin/console theme:change ProdataBaseTheme --all

  store:
    license-domain: 'example.com'