name: Code Quality

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shopware

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xdebug
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./shopware/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('shopware/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: make phpstan/analyze

      - name: Run ECS
        run: make ecs/check

      - name: Run PHPUnit
        run: make phpunit/analyze
        env:
          XDEBUG_MODE: coverage