name: Deployment

# Trigger on PR merge to develop
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Shopware CLI
        uses: shopware/shopware-cli-action@v1

      - name: Build
        run: shopware-cli project ci ./shopware

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy
          sub-directory: shopware
          deployer-binary: /usr/local/bin/dep
          deployer-version: 7.5.12
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-config: |
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USERNAME }}
            Port 3434
#            StrictHostKeyChecking accept-new // use a fingerprint known for now. use this only in dev envs

      - name: Setup SSH
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p $(getent passwd $(whoami) | cut -d : -f 6)/.ssh/
          echo "${{ env.SSH_KNOWN_HOSTS }}" >> $(getent passwd $(whoami) | cut -d : -f 6)/.ssh/known_hosts
          chmod 700 $(getent passwd $(whoami) | cut -d : -f 6)/.ssh/
          chmod 644 $(getent passwd $(whoami) | cut -d : -f 6)/.ssh/known_hosts

      - name: Success notification
        run: echo "✅ Deployment completed!"

#          - name: Deploy to server
#            uses: appleboy/ssh-action@v1.0.0
#            with:
#              host: ${{ secrets.HOST }}
#              username: ${{ secrets.USERNAME }}
#              key: ${{ secrets.SSH_PRIVATE_KEY }}
#              port: 3434
#              script: |
#                cd /var/www/html/nirvana
#                git pull origin develop
